package cn.emay.sdk.api;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SDKClient", targetNamespace = "http://sdkhttp.eucp.b2m.cn/")
public interface SDKClient {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getVersion", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetVersion")
	@ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetVersionResponse")
	public String getVersion();

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<cn.emay.sdk.api.StatusReport>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getReport", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetReport")
	@ResponseWrapper(localName = "getReportResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetReportResponse")
	public List<StatusReport> getReport(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "cancelMOForward", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.CancelMOForward")
	@ResponseWrapper(localName = "cancelMOForwardResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.CancelMOForwardResponse")
	public int cancelMOForward(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "chargeUp", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.ChargeUp")
	@ResponseWrapper(localName = "chargeUpResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.ChargeUpResponse")
	public int chargeUp(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns double
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getBalance", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetBalance")
	@ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetBalanceResponse")
	public double getBalance(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns double
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getEachFee", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetEachFee")
	@ResponseWrapper(localName = "getEachFeeResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetEachFeeResponse")
	public double getEachFee(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<cn.emay.sdk.api.Mo>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getMO", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetMO")
	@ResponseWrapper(localName = "getMOResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.GetMOResponse")
	public List<Mo> getMO(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "logout", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.Logout")
	@ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.LogoutResponse")
	public int logout(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg5
	 * @param arg3
	 * @param arg1
	 * @param arg7
	 * @param arg9
	 * @param arg6
	 * @param arg0
	 * @param arg2
	 * @param arg4
	 * @param arg8
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "registDetailInfo", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.RegistDetailInfo")
	@ResponseWrapper(localName = "registDetailInfoResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.RegistDetailInfoResponse")
	public int registDetailInfo(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4,
			@WebParam(name = "arg5", targetNamespace = "") String arg5,
			@WebParam(name = "arg6", targetNamespace = "") String arg6,
			@WebParam(name = "arg7", targetNamespace = "") String arg7,
			@WebParam(name = "arg8", targetNamespace = "") String arg8,
			@WebParam(name = "arg9", targetNamespace = "") String arg9);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "registEx", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.RegistEx")
	@ResponseWrapper(localName = "registExResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.RegistExResponse")
	public int registEx(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg5
	 * @param arg3
	 * @param arg1
	 * @param arg7
	 * @param arg6
	 * @param arg0
	 * @param arg2
	 * @param arg4
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sendSMS", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.SendSMS")
	@ResponseWrapper(localName = "sendSMSResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.SendSMSResponse")
	public int sendSMS(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") List<String> arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4,
			@WebParam(name = "arg5", targetNamespace = "") String arg5,
			@WebParam(name = "arg6", targetNamespace = "") String arg6,
			@WebParam(name = "arg7", targetNamespace = "") int arg7);

	/**
	 * 
	 * @param arg3
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "serialPwdUpd", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.SerialPwdUpd")
	@ResponseWrapper(localName = "serialPwdUpdResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.SerialPwdUpdResponse")
	public int serialPwdUpd(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setMOForward", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.SetMOForward")
	@ResponseWrapper(localName = "setMOForwardResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.SetMOForwardResponse")
	public int setMOForward(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @param arg2
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setMOForwardEx", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.SetMOForwardEx")
	@ResponseWrapper(localName = "setMOForwardExResponse", targetNamespace = "http://sdkhttp.eucp.b2m.cn/", className = "cn.emay.sdk.api.SetMOForwardExResponse")
	public int setMOForwardEx(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<String> arg2);

}
